// templates.js
// Pre-configured workflow pipeline templates for instant demonstration

export const PIPELINE_TEMPLATES = [
  {
    id: 'ai-qa',
    name: '🤖 AI Q&A Chain',
    description: 'User input passed through dynamic prompt template into LLM and streamed to output.',
    nodes: [
      {
        id: 'customInput-1',
        type: 'customInput',
        position: { x: 80, y: 180 },
        data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'user_query', inputType: 'Text' },
      },
      {
        id: 'text-1',
        type: 'text',
        position: { x: 380, y: 150 },
        data: {
          id: 'text-1',
          nodeType: 'text',
          text: 'Answer the following query concisely and accurately:\n\nQuery: {{user_query}}',
        },
      },
      {
        id: 'llm-1',
        type: 'llm',
        position: { x: 740, y: 160 },
        data: { id: 'llm-1', nodeType: 'llm' },
      },
      {
        id: 'customOutput-1',
        type: 'customOutput',
        position: { x: 1040, y: 180 },
        data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'ai_response', outputType: 'Text' },
      },
    ],
    edges: [
      {
        id: 'e-in-text',
        source: 'customInput-1',
        sourceHandle: 'customInput-1-value',
        target: 'text-1',
        targetHandle: 'text-1-user_query',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-text-llm',
        source: 'text-1',
        sourceHandle: 'text-1-output',
        target: 'llm-1',
        targetHandle: 'llm-1-prompt',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-llm-out',
        source: 'llm-1',
        sourceHandle: 'llm-1-response',
        target: 'customOutput-1',
        targetHandle: 'customOutput-1-value',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
    ],
    nodeIDs: { customInput: 1, text: 1, llm: 1, customOutput: 1 },
  },
  {
    id: 'doc-summarizer',
    name: '📑 Summarizer & Classifier',
    description: 'Document extraction, LLM summarization, condition filter, rate delay, and output.',
    nodes: [
      {
        id: 'customInput-1',
        type: 'customInput',
        position: { x: 60, y: 200 },
        data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'raw_doc', inputType: 'File' },
      },
      {
        id: 'text-1',
        type: 'text',
        position: { x: 340, y: 170 },
        data: {
          id: 'text-1',
          nodeType: 'text',
          text: 'Extract key executive takeaways from:\n{{raw_doc}}',
        },
      },
      {
        id: 'llm-1',
        type: 'llm',
        position: { x: 680, y: 180 },
        data: { id: 'llm-1', nodeType: 'llm' },
      },
      {
        id: 'filter-1',
        type: 'filter',
        position: { x: 970, y: 180 },
        data: { id: 'filter-1', nodeType: 'filter', condition: 'confidence > 0.85' },
      },
      {
        id: 'timer-1',
        type: 'timer',
        position: { x: 1240, y: 190 },
        data: { id: 'timer-1', nodeType: 'timer', seconds: 2 },
      },
      {
        id: 'customOutput-1',
        type: 'customOutput',
        position: { x: 1510, y: 200 },
        data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'final_summary', outputType: 'Text' },
      },
    ],
    edges: [
      {
        id: 'e-in-text',
        source: 'customInput-1',
        sourceHandle: 'customInput-1-value',
        target: 'text-1',
        targetHandle: 'text-1-raw_doc',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-text-llm',
        source: 'text-1',
        sourceHandle: 'text-1-output',
        target: 'llm-1',
        targetHandle: 'llm-1-prompt',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-llm-filter',
        source: 'llm-1',
        sourceHandle: 'llm-1-response',
        target: 'filter-1',
        targetHandle: 'filter-1-input',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-filter-timer',
        source: 'filter-1',
        sourceHandle: 'filter-1-output',
        target: 'timer-1',
        targetHandle: 'timer-1-input',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-timer-out',
        source: 'timer-1',
        sourceHandle: 'timer-1-output',
        target: 'customOutput-1',
        targetHandle: 'customOutput-1-value',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
    ],
    nodeIDs: { customInput: 1, text: 1, llm: 1, filter: 1, timer: 1, customOutput: 1 },
  },
  {
    id: 'api-enrich',
    name: '🌐 API Data Transformer',
    description: 'Fetch external REST data, apply filter logic and math calculations.',
    nodes: [
      {
        id: 'api-1',
        type: 'api',
        position: { x: 80, y: 160 },
        data: { id: 'api-1', nodeType: 'api', url: 'https://api.github.com/repos/PTP063/Visflow', method: 'GET' },
      },
      {
        id: 'filter-1',
        type: 'filter',
        position: { x: 380, y: 160 },
        data: { id: 'filter-1', nodeType: 'filter', condition: 'status === 200' },
      },
      {
        id: 'math-1',
        type: 'math',
        position: { x: 670, y: 150 },
        data: { id: 'math-1', nodeType: 'math', operation: 'Multiply' },
      },
      {
        id: 'customOutput-1',
        type: 'customOutput',
        position: { x: 970, y: 180 },
        data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'processed_data', outputType: 'Text' },
      },
    ],
    edges: [
      {
        id: 'e-api-filter',
        source: 'api-1',
        sourceHandle: 'api-1-response',
        target: 'filter-1',
        targetHandle: 'filter-1-input',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-filter-math',
        source: 'filter-1',
        sourceHandle: 'filter-1-output',
        target: 'math-1',
        targetHandle: 'math-1-a',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
      {
        id: 'e-math-out',
        source: 'math-1',
        sourceHandle: 'math-1-result',
        target: 'customOutput-1',
        targetHandle: 'customOutput-1-value',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#818cf8', strokeWidth: 2 },
      },
    ],
    nodeIDs: { api: 1, filter: 1, math: 1, customOutput: 1 },
  },
];
